---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: docker-k8s-demo
      tier: frontend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: docker-k8s-demo
        tier: frontend
        track: stable
    spec:
      containers:
        - name: frontend-demo
          image: "fsouayah/demo-frontend:latest"
          lifecycle:
            preStop:
              exec:
                command: ["/usr/sbin/nginx","-s","quit"]